In [2]:
import numpy as np
import pandas as pd

In [4]:
test = np.load("data/AWA2_test_continuous_01_attributelabel.npy")
print(test[0])

[0.22020529 0.52877251 0.44712103 0.10824295 0.45480529 0.
 0.         0.         0.21106533 0.0625     0.06322072 1.
 0.         0.07311688 0.06606765 0.48832074 0.40107212 0.19787697
 0.         0.         0.         1.         0.90337403 0.10582074
 0.09047668 0.75656031 0.47419654 0.48043782 0.         0.
 0.         0.7419054  0.         0.0786     0.         0.07135518
 0.06834336 0.         0.83257288 0.29579507 0.67229582 0.14169858
 0.48125815 0.15180957 0.10901163 0.74325843 0.14968068 0.91458411
 0.10671657 0.01811005 0.48319774 0.47953918 0.33172358 0.
 0.08006662 0.10768899 0.08115829 0.07944579 0.12928294 0.08348398
 0.         0.1035313  0.60258502 0.57905025 0.         0.02349958
 0.27777778 0.09602089 0.15325392 0.11602067 0.13929284 0.06794955
 0.09301979 0.         0.56226326 0.01389661 0.03244838 0.
 0.16680587 0.64735516 0.39505356 0.07754342 0.61543635 0.1638796
 0.87229204]


In [6]:
predicate_labels_cont = np.loadtxt("../food_label_vector.txt")
#print(predicate_labels_cont[0])
#normalization
pred_normed = predicate_labels_cont / predicate_labels_cont.max(axis=0)
np.savetxt("../food-label-vector-normed.txt", pred_normed)

In [18]:
#split classes, create attribute lable
#check labels:
labels = np.loadtxt("../../AwA2-features/ResNet101/AwA2-labels.txt")
print(labels.shape[0])
for i in range(labels.shape[0]):
    

37322


In [5]:
# 提取binary test label(10x85):
test = np.load("data/AWA2_test_attributlabel.npy")
ret = []
labels = [5, 13, 14, 17, 23, 24, 33, 38, 41, 47]
for idx in labels:
    ret.append(test[idx])
ret = np.array(ret)
print(ret.shape)
np.save("data/bi_te_att_10_85.npy", ret)

(10, 85)


In [13]:
#word vector的consine distance有多少？
gt = np.loadtxt("../food_label_vector.txt")

dist_list = np.zeros((11,11), dtype = float)
labels = []
for i in range(gt.shape[0]):
    for j in range (i + 1, gt.shape[0]):
        dist = 1 - np.dot(gt[i],gt[j].transpose())/(np.linalg.norm(gt[i])*np.linalg.norm(gt[j]))
        dist_list[i][j] = dist
dist_list = np.around(dist_list, decimals=3)
np.set_printoptions(threshold=10000)
print(dist_list)


[[0.    0.562 0.385 0.439 0.427 0.379 0.37  0.391 0.563 0.366 0.363]
 [0.    0.    0.591 0.528 0.67  0.372 0.668 0.548 0.54  0.644 0.439]
 [0.    0.    0.    0.572 0.509 0.552 0.436 0.559 0.513 0.394 0.406]
 [0.    0.    0.    0.    0.483 0.43  0.462 0.479 0.609 0.459 0.436]
 [0.    0.    0.    0.    0.    0.419 0.377 0.381 0.421 0.407 0.51 ]
 [0.    0.    0.    0.    0.    0.    0.41  0.425 0.37  0.404 0.352]
 [0.    0.    0.    0.    0.    0.    0.    0.368 0.376 0.224 0.418]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.499 0.372 0.37 ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.439 0.472]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.391]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]]
